using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DiscModelParams_Cn
{
    // the current params, ingredients for making a discModel...for the MakeDiscsModel script 
        // the actual discModel is stored in a List< DiscModel_Cn >
        // each LightDiscMovement script randomly selects one of those DiscModel_Cn's
    public float funds_harmonicity;
    public float funds_deformation;
    public float funds_size;
    public float funds_lowest;
    public float funds_highestAllowed;
    // deviation of the cloud of fundamentals:
    // 0. = no deviation from the funds generated by the virtual_fund 
    // > 0. is a midi number random deviation, an ever wider range of possibility
    public float funds_MIDIdeviation_range;
    public float parts_harmonicity;
    public float parts_deformation;
    public float parts_size;
    public float parts_highestAllowed;
    public float parts_MIDIdeviation_range;
    [Range(0.0f, 1.0f)]
    public float parts_include_prob;
    // 0 = unison with fund; 1.0 = critical band; closer to 1 = rougher beatings/shimmer
    public Vector2 lightFlareEvent_shimmer_percentOfCriticalBandRange;

    // params that the MakeDiscsModel script just pass on to the lightDiscMovement scripts:
        // e.g. noneOrTwoOctavesLower: in each lightDiscMovement script, random select either no transp or 2 octaves lower
    public enum ModelTransposition { none, twoOctavesLower, oneOctaveLower, oneOrTwoOctavesLower, noneOrTwoOctavesLower, noneOrOneOctaveLower, oneOctaveHigher, noneOrOneOctaveHigher };
    public ModelTransposition modelTransposition;
    public float ampGlobal;
}
